### PR TITLE
Awesome book  with navigation

### PR DESCRIPTION
**Pull request by hiwina**
New features added on Awesome books
- [ ] Added a navigation bar
- [ ] Added three content sections which can be accessed with the links in the navigation

### CODE REVIEW

**Review by roshan-bajgain — COMMENTED** [review]
Hi @hiwina, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you did alone but this is pair programming. please do with your partner.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏a

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by solorics** [comment]
### **Awesome books: a complete website with navigation** 💯 

>. We ensure that when a user clicks on any of the links, the main area changes to display only one of the three content sections. 💯 ✅ 
 >. used only plain JavaScript and CSS. 💯 ✅

**Review by peterrobert — CHANGES_REQUESTED** [review]
Hi @hiwina and @solorics , 

Very nice project. I love the way you have separated your code into modules and assigned specific tasks to specific modules 👏🏿 . However, there are a few changes to be made kindly check below ⬇️

### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] It will be great to update the main area of the app with only the content of your selection. For example, when you select the list, only the information about listing all books should be visible. When any of the links are clicked, the main area changes to display only one of the three content sections.  At the moment what your implementation is doing is just pointing to that section. However, the content of the page doesn't change

- [ ] It will be good to remove all those eslint disable lines. Instead of disabling the linters kindly fix the issues in the code.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by solorics** [comment]
### Project requirements 💯 ✅ 
**Modify the Awesome books application to have:** 💯 
>. A Navigation bar. 💯 ✅ 
>. Three content sections: 💯 ✅ 
>. Books list. 👍 
Add book form. 👍 
Contact info. 👍 



Screenshot 2022-12-09 at 11 37 09
Screenshot 2022-12-09 at 11 30 54
Screenshot 2022-12-09 at 11 31 15
Screenshot 2022-12-09 at 11 31 40
Screenshot 2022-12-09 at 11 31 46
Screenshot 2022-12-09 at 11 32 14
Screenshot 2022-12-09 at 11 32 30
Screenshot 2022-12-09 at 11 32 44
 >. _We Ensure that when the user clicks on any of the links, the main area changes to display only one of the three content 👍 💯 sections. ✅_ 
>. Screenshots added above for better view 💯

**Review by Qoosim — APPROVED** [review]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
